
export interface Product {
    id: string;
    name: string;
    category: string;
    price: number;
    originalPrice?: number;
    image: string;
    description: string;
    weight: string;
    rating: number;
    reviews: number;
    badges?: string[];
    tag?: string;
    brand?: string;
    offerValidity?: string;
    isReturnable?: boolean | number;
}

export const categories = [
    { id: "all", name: "All Categories" },
    { id: "vegetables", name: "Vegetables" },
    { id: "fruits", name: "Fruits" },
    { id: "baby_products", name: "Baby Products" },
    { id: "dairy", name: "Dairy" },
    { id: "beverages", name: "Beverages" },
    { id: "food_cupboard", name: "Food Cupboard" },
    { id: "household", name: "Household" },
    { id: "cooking_essentials", name: "Cooking Essentials" },
    { id: "bakery", name: "Bakery" },
    { id: "frozen_food", name: "Frozen Food" },
    { id: "meats", name: "Meats" },
    { id: "seafood", name: "Seafood" },
    { id: "snacks_confectionery", name: "Snacks & Confectionery" },
];

export const products: Product[] = [
    // 🥕 Vegetables
    {
        id: "veg_1",
        name: "Fresh Potatoes",
        category: "vegetables",
        price: 4.50,
        image: "/images/products/apple.png",
        description: "Farm fresh organic potatoes.",
        weight: "1kg",
        rating: 4.5,
        reviews: 120,
        tag: "Fresh Potatoes",


    },
    {
        id: "veg_2",
        name: "Red Onions",
        category: "vegetables",
        price: 3.20,
        image: "/images/products/apple.png",
        description: "Sharp and flavorful red onions.",
        weight: "500g",
        rating: 4.6,
        reviews: 85,
        tag: "RED ONIONS"
    },
    {
        id: "veg_3",
        name: "Crunchy Carrots",
        category: "vegetables",
        price: 2.80,
        image: "/images/products/apple.png",
        description: "Sweet and crunchy organic carrots.",
        weight: "500g",
        rating: 4.7,
        reviews: 95,
        tag: "CRUNCHY CARROTS"

    },
    {
        id: "veg_4",
        name: "Green Cabbage",
        category: "vegetables",
        price: 3.50,
        image: "/images/products/apple.png",
        description: "Freshly harvested green cabbage.",
        weight: "1 Unit",
        rating: 4.4,
        reviews: 40,
        tag: "GREEN CABBAGE"

    },
    {
        id: "veg_5",
        name: "Green Beans",
        category: "vegetables",
        price: 5.20,
        image: "/images/products/apple.png",
        description: "Tender and fresh green beans.",
        weight: "250g",
        rating: 4.5,
        reviews: 30,
        tag: "GREEN BEANS"

    },

    // 🍎 Fruits
    {
        id: "1",
        name: "Fresh Red Apple",
        category: "fruits",
        price: 250.00,
        originalPrice: 350.00,
        image: "/images/products/apple.png",
        rating: 5,
        reviews: 85,
        description: "Sweet and crisp fresh red apples, perfect for snacking or baking.",
        weight: "1kg"
    },
    {
        id: "2",
        name: "Organic Cabbage",
        category: "vegetables",
        price: 80.00,
        originalPrice: 100.00,
        image: "/images/products/apple.png",
        rating: 4,
        reviews: 62,
        description: "Fresh organic cabbage, rich in vitamins and perfect for salads.",
        weight: "1pc"
    },
    {
        id: "3",
        name: "Fresh Tomato",
        category: "vegetables",
        price: 150.00,
        image: "/images/products/apple.png",
        rating: 5,
        reviews: 94,
        description: "Ripe and juicy fresh tomatoes, essential for your daily cooking.",
        weight: "1kg"
    },
    {
        id: "4",
        name: "Sweet Litchi",
        category: "fruits",
        price: 450.00,
        originalPrice: 500.00,
        image: "/images/products/apple.png",
        rating: 4,
        reviews: 47,
        description: "Seasonal sweet litchis, bursting with flavor.",
        weight: "500g"
    },
    {
        id: "5",
        name: "Premium Almonds",
        category: "food_cupboard",
        price: 1200.00,
        image: "/images/products/apple.png",
        rating: 5,
        reviews: 128,
        description: "High-quality premium almonds, great for health and wellness.",
        weight: "250g"
    },
    // 👶 Baby Products
    {
        id: "baby_1",
        name: "Superior Baby Milk Powder",
        category: "baby_products",
        price: 28.50,
        image: "/images/products/apple.png",
        description: "Nutritious formula for infants.",
        weight: "400g",
        rating: 4.9,
        reviews: 150,
    },
    {
        id: "baby_2",
        name: "Ultra Absorb Baby Diapers",
        category: "baby_products",
        price: 19.99,
        image: "/images/products/apple.png",
        description: "Soft and breathable protection.",
        weight: "Large (44 Pcs)",
        rating: 4.8,
        reviews: 320,
    },
    {
        id: "baby_3",
        name: "Soft Touch Baby Wipes",
        category: "baby_products",
        price: 5.50,
        image: "/images/products/apple.png",
        description: "Fragrance-free sensitive wipes.",
        weight: "80 Sheets",
        rating: 4.7,
        reviews: 210,
    },
    {
        id: "baby_4",
        name: "Gentle Baby Soap",
        category: "baby_products",
        price: 3.20,
        image: "/images/products/apple.png",
        description: "Mild and gentle for baby skin.",
        weight: "100g",
        rating: 4.8,
        reviews: 95,
    },
    {
        id: "baby_5",
        name: "Baby Food Cereal",
        category: "baby_products",
        price: 8.50,
        image: "/images/products/apple.png",
        description: "Mixed fruit baby cereal.",
        weight: "200g",
        rating: 4.6,
        reviews: 140,
    },

    // 🥛 Dairy
    {
        id: "dairy_1",
        name: "Fresh Full Cream Milk",
        category: "dairy",
        price: 3.50,
        image: "/images/products/apple.png",
        description: "Pasteurized fresh milk.",
        weight: "1L",
        rating: 4.9,
        reviews: 500,
    },
    {
        id: "dairy_2",
        name: "Powdered Instant Milk",
        category: "dairy",
        price: 12.00,
        image: "/images/products/apple.png",
        description: "High calcium milk powder.",
        weight: "400g",
        rating: 4.7,
        reviews: 180,
    },
    {
        id: "dairy_3",
        name: "Natural Yogurt",
        category: "dairy",
        price: 1.80,
        image: "/images/products/apple.png",
        description: "Creamy and delicious yogurt.",
        weight: "150g",
        rating: 4.8,
        reviews: 240,
    },
    {
        id: "dairy_4",
        name: "Cheddar Cheese Block",
        category: "dairy",
        price: 8.90,
        image: "/images/products/apple.png",
        description: "Sharp and rich cheddar cheese.",
        weight: "250g",
        rating: 4.8,
        reviews: 130,
    },
    {
        id: "dairy_5",
        name: "Salted Butter",
        category: "dairy",
        price: 6.40,
        image: "/images/products/apple.png",
        description: "Creamy pure dairy butter.",
        weight: "200g",
        rating: 4.9,
        reviews: 190,
    },

    // 🥤 Beverages
    {
        id: "bev_1",
        name: "Pure Ceylon Tea",
        category: "beverages",
        price: 4.80,
        image: "/images/products/apple.png",
        description: "Strong and aromatic black tea.",
        weight: "400g",
        rating: 4.9,
        reviews: 300,
    },
    {
        id: "bev_2",
        name: "Roasted Ground Coffee",
        category: "beverages",
        price: 9.50,
        image: "/images/products/apple.png",
        description: "Dark roast ground coffee.",
        weight: "200g",
        rating: 4.8,
        reviews: 120,
    },
    {
        id: "bev_3",
        name: "Milo Energy Drink",
        category: "beverages",
        price: 11.20,
        image: "/images/products/apple.png",
        description: "Chocolate malt energy drink.",
        weight: "400g",
        rating: 4.9,
        reviews: 600,
    },
    {
        id: "bev_4",
        name: "Mixed Fruit Juice",
        category: "beverages",
        price: 3.50,
        image: "/images/products/apple.png",
        description: "100% natural fruit juice.",
        weight: "1L",
        rating: 4.7,
        reviews: 150,
    },
    {
        id: "bev_5",
        name: "Mineral Water",
        category: "beverages",
        price: 0.90,
        image: "/images/products/apple.png",
        description: "Refreshing mineral water.",
        weight: "1.5L",
        rating: 4.9,
        reviews: 800,
    },

    // 🧂 Food Cupboard (Dry Foods)
    {
        id: "cup_1",
        name: "Premium Basmati Rice",
        category: "food_cupboard",
        price: 15.00,
        image: "/images/products/apple.png",
        description: "Aromatic long grain basmati.",
        weight: "5kg",
        rating: 4.8,
        reviews: 400,
    },
    {
        id: "cup_2",
        name: "Red Lentils (Dhal)",
        category: "food_cupboard",
        price: 2.80,
        image: "/images/products/apple.png",
        description: "Rich and nutritious red lentils.",
        weight: "1kg",
        rating: 4.7,
        reviews: 200,
    },
    {
        id: "cup_3",
        name: "Organic Chickpeas",
        category: "food_cupboard",
        price: 3.50,
        image: "/images/products/apple.png",
        description: "High protein organic chickpeas.",
        weight: "1kg",
        rating: 4.6,
        reviews: 90,
    },
    {
        id: "cup_4",
        name: "Canned Mackerel Fish",
        category: "food_cupboard",
        price: 4.20,
        image: "/images/products/apple.png",
        description: "Fresh mackerel in tomato sauce.",
        weight: "425g",
        rating: 4.5,
        reviews: 130,
    },
    {
        id: "cup_5",
        name: "Italian Style Pasta",
        category: "food_cupboard",
        price: 2.50,
        image: "/images/products/apple.png",
        description: "Durum wheat semolina pasta.",
        weight: "500g",
        rating: 4.8,
        reviews: 310,
    },

    // 🧹 Household
    {
        id: "hh_1",
        name: "Laundry Liquid Detergent",
        category: "household",
        price: 14.50,
        image: "/images/products/apple.png",
        description: "Advanced stain removal formula.",
        weight: "2L",
        rating: 4.7,
        reviews: 200,
    },
    {
        id: "hh_2",
        name: "Dishwashing Liquid",
        category: "household",
        price: 3.80,
        image: "/images/products/apple.png",
        description: "Lemon fresh grease cutter.",
        weight: "500ml",
        rating: 4.6,
        reviews: 140,
    },
    {
        id: "hh_3",
        name: "Natural Soap Bars",
        category: "household",
        price: 5.20,
        image: "/images/products/apple.png",
        description: "Pk of 3 moisturizing soaps.",
        weight: "3 x 100g",
        rating: 4.8,
        reviews: 180,
    },
    {
        id: "hh_4",
        name: "Soft Toilet Paper",
        category: "household",
        price: 8.50,
        image: "/images/products/apple.png",
        description: "White 2-ply soft toilet rolls.",
        weight: "10 Rolls",
        rating: 4.5,
        reviews: 500,
    },
    {
        id: "hh_5",
        name: "Multi-Floor Cleaner",
        category: "household",
        price: 6.80,
        image: "/images/products/apple.png",
        description: "Antibacterial floor cleaning liquid.",
        weight: "1L",
        rating: 4.6,
        reviews: 110,
    },

    // 🍳 Cooking Essentials
    {
        id: "cook_1",
        name: "Pure Vegetable Oil",
        category: "cooking_essentials",
        price: 12.50,
        image: "/images/products/apple.png",
        description: "High quality cooking oil.",
        weight: "2L",
        rating: 4.8,
        reviews: 250,
    },
    {
        id: "cook_2",
        name: "Refined Table Salt",
        category: "cooking_essentials",
        price: 1.20,
        image: "/images/products/apple.png",
        description: "Pure iodized table salt.",
        weight: "1kg",
        rating: 4.9,
        reviews: 400,
    },
    {
        id: "cook_3",
        name: "White Fine Sugar",
        category: "cooking_essentials",
        price: 3.50,
        image: "/images/products/apple.png",
        description: "High quality white sugar.",
        weight: "1kg",
        rating: 4.7,
        reviews: 300,
    },
    {
        id: "cook_4",
        name: "Spiced Curry Powder",
        category: "cooking_essentials",
        price: 2.80,
        image: "/images/products/apple.png",
        description: "Traditional aromatic curry blend.",
        weight: "100g",
        rating: 4.8,
        reviews: 180,
    },
    {
        id: "cook_5",
        name: "Extra Hot Chili Powder",
        category: "cooking_essentials",
        price: 2.50,
        image: "/images/products/apple.png",
        description: "Fine ground red chili powder.",
        weight: "100g",
        rating: 4.7,
        reviews: 110,
    },

    // 🥐 Bakery
    {
        id: "bak_1",
        name: "Soft White Bread",
        category: "bakery",
        price: 2.10,
        image: "/images/products/apple.png",
        description: "Baked fresh every morning.",
        weight: "450g",
        rating: 4.8,
        reviews: 600,
    },
    {
        id: "bak_2",
        name: "Sweet Buns",
        category: "bakery",
        price: 3.50,
        image: "/images/products/apple.png",
        description: "Soft sweet tea buns.",
        weight: "Pk 6",
        rating: 4.6,
        reviews: 90,
    },
    {
        id: "bak_3",
        name: "Crunchy Cake Rusk",
        category: "bakery",
        price: 5.20,
        image: "/images/products/apple.png",
        description: "Twice-baked crunchy rusk.",
        weight: "200g",
        rating: 4.7,
        reviews: 140,
    },
    {
        id: "bak_4",
        name: "Vanilla Cup Cakes",
        category: "bakery",
        price: 6.80,
        image: "/images/products/apple.png",
        description: "Moist vanilla cupcakes with icing.",
        weight: "Pk 6",
        rating: 4.8,
        reviews: 130,
    },
    {
        id: "bak_5",
        name: "Sweet Fruit Bread",
        category: "bakery",
        price: 4.50,
        image: "/images/products/apple.png",
        description: "Enriched bread with dried fruits.",
        weight: "400g",
        rating: 4.7,
        reviews: 110,
    },

    // ❄️ Frozen Food
    {
        id: "froz_1",
        name: "Frozen Whole Chicken",
        category: "frozen_food",
        price: 13.50,
        image: "/images/products/apple.png",
        description: "Cleaned and fresh frozen chicken.",
        weight: "1.2kg",
        rating: 4.7,
        reviews: 210,
    },
    {
        id: "froz_2",
        name: "Frozen Fish Fillets",
        category: "frozen_food",
        price: 18.00,
        image: "/images/products/apple.png",
        description: "Individually quick frozen fish.",
        weight: "1kg",
        rating: 4.6,
        reviews: 95,
    },
    {
        id: "froz_3",
        name: "Mixed Frozen Vegetables",
        category: "frozen_food",
        price: 5.20,
        image: "/images/products/apple.png",
        description: "Peas, corn and carrot mix.",
        weight: "500g",
        rating: 4.8,
        reviews: 180,
    },
    {
        id: "froz_4",
        name: "Frozen Chicken Sausages",
        category: "frozen_food",
        price: 7.50,
        image: "/images/products/apple.png",
        description: "Premium chicken breakfast sausages.",
        weight: "500g",
        rating: 4.5,
        reviews: 140,
    },
    {
        id: "froz_5",
        name: "Frozen Chicken Nuggets",
        category: "frozen_food",
        price: 9.90,
        image: "/images/products/apple.png",
        description: "Crispy battered chicken nuggets.",
        weight: "500g",
        rating: 4.9,
        reviews: 300,
    },

    // 🍖 Meats
    {
        id: "meat_1",
        name: "Fresh Whole Chicken",
        category: "meats",
        price: 12.00,
        image: "/images/products/apple.png",
        description: "Farm raised fresh chicken.",
        weight: "1kg",
        rating: 4.8,
        reviews: 400,
    },
    {
        id: "meat_2",
        name: "Premium Beef Stew",
        category: "meats",
        price: 18.50,
        image: "/images/products/apple.png",
        description: "Tender beef cubes for stewing.",
        weight: "500g",
        rating: 4.9,
        reviews: 150,
    },
    {
        id: "meat_3",
        name: "Fresh Mutton Shoulder",
        category: "meats",
        price: 24.00,
        image: "/images/products/apple.png",
        description: "High quality fresh mutton.",
        weight: "500g",
        rating: 4.7,
        reviews: 65,
    },
    {
        id: "meat_4",
        name: "Tender Pork Ribs",
        category: "meats",
        price: 16.50,
        image: "/images/products/apple.png",
        description: "Fresh and fatty pork ribs.",
        weight: "500g",
        rating: 4.8,
        reviews: 80,
    },
    {
        id: "meat_5",
        name: "Lean Minced Meat",
        category: "meats",
        price: 14.20,
        image: "/images/products/apple.png",
        description: "Finely ground lean beef.",
        weight: "500g",
        rating: 4.6,
        reviews: 110,
    },

    // 🐟 Seafood
    {
        id: "sea_1",
        name: "Fresh Sea Fish",
        category: "seafood",
        price: 9.80,
        image: "/images/products/apple.png",
        description: "Local sea fish of the day.",
        weight: "1kg",
        rating: 4.7,
        reviews: 130,
    },
    {
        id: "sea_2",
        name: "Large King Prawns",
        category: "seafood",
        price: 22.00,
        image: "/images/products/apple.png",
        description: "Premium large king prawns.",
        weight: "500g",
        rating: 4.9,
        reviews: 180,
    },
    {
        id: "sea_3",
        name: "Fresh Cuttlefish",
        category: "seafood",
        price: 14.50,
        image: "/images/products/apple.png",
        description: "Cleaned and fresh cuttlefish.",
        weight: "500g",
        rating: 4.6,
        reviews: 55,
    },
    {
        id: "sea_4",
        name: "Aromatic Dry Fish",
        category: "seafood",
        price: 6.80,
        image: "/images/products/apple.png",
        description: "Traditional sun-dried salted fish.",
        weight: "100g",
        rating: 4.5,
        reviews: 40,
    },
    {
        id: "sea_5",
        name: "Fresh Lagoon Crab",
        category: "seafood",
        price: 28.00,
        image: "/images/products/apple.png",
        description: "Succulent fresh water lagoon crabs.",
        weight: "1 Unit (Approx 500g)",
        rating: 4.8,
        reviews: 90,
    },

    // 🍫 Snacks & Confectionery
    {
        id: "snack_1",
        name: "Bite-size Biscuits",
        category: "snacks_confectionery",
        price: 2.50,
        image: "/images/products/apple.png",
        description: "Crispy sweet biscuits.",
        weight: "200g",
        rating: 4.7,
        reviews: 450,
    },
    {
        id: "snack_2",
        name: "Hazelnut Chocolates",
        category: "snacks_confectionery",
        price: 7.20,
        image: "/images/products/apple.png",
        description: "Rich chocolate with hazelnut centers.",
        weight: "150g",
        rating: 4.9,
        reviews: 300,
    },
    {
        id: "snack_3",
        name: "Creamy Wafers",
        category: "snacks_confectionery",
        price: 3.80,
        image: "/images/products/apple.png",
        description: "Layered wafers with cream filling.",
        weight: "15g",
        rating: 4.6,
        reviews: 140,
    },
    {
        id: "snack_4",
        name: "Fruit Gummies",
        category: "snacks_confectionery",
        price: 4.50,
        image: "/images/products/apple.png",
        description: "Chewy and colorful fruit flavored jelly.",
        weight: "100g",
        rating: 4.8,
        reviews: 210,
    },
    {
        id: "snack_5",
        name: "Spicy Murukku Snack",
        category: "snacks_confectionery",
        price: 2.20,
        image: "/images/products/apple.png",
        description: "Traditional spicy savory murukku.",
        weight: "150g",
        rating: 4.7,
        reviews: 180,
    }
];
