export const countries = [
  {
    id: 0,
    name: "Select a country",
    countryCode: "",
    currency: "",
    flag: "",
  },
  {
    id: 1,
    name: "Afghanistan",
    countryCode: "AF",
    currency: "AFN",
    flag: "🇦🇫",
  },
  {
    id: 2,
    name: "Åland Islands",
    countryCode: "AX",
    currency: "EUR",
    flag: "🇦🇽",
  },
  {
    id: 3,
    name: "Albania",
    countryCode: "AL",
    currency: "ALL",
    flag: "🇦🇱",
  },
  {
    id: 4,
    name: "Algeria",
    countryCode: "DZ",
    currency: "DZD",
    flag: "🇩🇿",
  },
  {
    id: 5,
    name: "American Samoa",
    countryCode: "AS",
    currency: "USD",
    flag: "🇦🇸",
  },
  {
    id: 6,
    name: "Andorra",
    countryCode: "AD",
    currency: "EUR",
    flag: "🇦🇩",
  },
  {
    id: 7,
    name: "Angola",
    countryCode: "AO",
    currency: "AOA",
    flag: "🇦🇴",
  },
  {
    id: 8,
    name: "Anguilla",
    countryCode: "AI",
    currency: "XCD",
    flag: "🇦🇮",
  },
  {
    id: 9,
    name: "Antarctica",
    countryCode: "AQ",
    currency: "",
    flag: "🇦🇶",
  },
  {
    id: 10,
    name: "Antigua and Barbuda",
    countryCode: "AG",
    currency: "XCD",
    flag: "🇦🇬",
  },
  {
    id: 11,
    name: "Argentina",
    countryCode: "AR",
    currency: "ARS",
    flag: "🇦🇷",
  },
  {
    id: 12,
    name: "Armenia",
    countryCode: "AM",
    currency: "AMD",
    flag: "🇦🇲",
  },
  {
    id: 13,
    name: "Aruba",
    countryCode: "AW",
    currency: "AWG",
    flag: "🇦🇼",
  },
  {
    id: 14,
    name: "Australia",
    countryCode: "AU",
    currency: "AUD",
    flag: "🇦🇺",
  },
  {
    id: 15,
    name: "Austria",
    countryCode: "AT",
    currency: "EUR",
    flag: "🇦🇹",
  },
  {
    id: 16,
    name: "Azerbaijan",
    countryCode: "AZ",
    currency: "AZN",
    flag: "🇦🇿",
  },
  {
    id: 17,
    name: "Bahamas",
    countryCode: "BS",
    currency: "BSD",
    flag: "🇧🇸",
  },
  {
    id: 18,
    name: "Bahrain",
    countryCode: "BH",
    currency: "BHD",
    flag: "🇧🇭",
  },
  {
    id: 19,
    name: "Bangladesh",
    countryCode: "BD",
    currency: "BDT",
    flag: "🇧🇩",
  },
  {
    id: 20,
    name: "Barbados",
    countryCode: "BB",
    currency: "BBD",
    flag: "🇧🇧",
  },
  {
    id: 21,
    name: "Belarus",
    countryCode: "BY",
    currency: "BYN",
    flag: "🇧🇾",
  },
  {
    id: 22,
    name: "Belgium",
    countryCode: "BE",
    currency: "EUR",
    flag: "🇧🇪",
  },
  {
    id: 23,
    name: "Belize",
    countryCode: "BZ",
    currency: "BZD",
    flag: "🇧🇿",
  },
  {
    id: 24,
    name: "Benin",
    countryCode: "BJ",
    currency: "XOF",
    flag: "🇧🇯",
  },
  {
    id: 25,
    name: "Bermuda",
    countryCode: "BM",
    currency: "BMD",
    flag: "🇧🇲",
  },
  {
    id: 26,
    name: "Bhutan",
    countryCode: "BT",
    currency: "BTN",
    flag: "🇧🇹",
  },
  {
    id: 27,
    name: "Bolivia (Plurinational State of)",
    countryCode: "BO",
    currency: "BOB",
    flag: "🇧🇴",
  },
  {
    id: 28,
    name: "Bonaire, Sint Eustatius and Saba",
    countryCode: "BQ",
    currency: "USD",
    flag: "🇧🇶",
  },
  {
    id: 29,
    name: "Bosnia and Herzegovina",
    countryCode: "BA",
    currency: "BAM",
    flag: "🇧🇦",
  },
  {
    id: 30,
    name: "Botswana",
    countryCode: "BW",
    currency: "BWP",
    flag: "🇧🇼",
  },
  {
    id: 31,
    name: "Bouvet Island",
    countryCode: "BV",
    currency: "NOK",
    flag: "🇧🇻",
  },
  {
    id: 32,
    name: "Brazil",
    countryCode: "BR",
    currency: "BRL",
    flag: "🇧🇷",
  },
  {
    id: 33,
    name: "British Indian Ocean Territory",
    countryCode: "IO",
    currency: "USD",
    flag: "🇮🇴",
  },
  {
    id: 34,
    name: "Brunei Darussalam",
    countryCode: "BN",
    currency: "BND",
    flag: "🇧🇳",
  },
  {
    id: 35,
    name: "Bulgaria",
    countryCode: "BG",
    currency: "BGN",
    flag: "🇧🇬",
  },
  {
    id: 36,
    name: "Burkina Faso",
    countryCode: "BF",
    currency: "XOF",
    flag: "🇧🇫",
  },
  {
    id: 37,
    name: "Burundi",
    countryCode: "BI",
    currency: "BIF",
    flag: "🇧🇮",
  },
  {
    id: 38,
    name: "Cabo Verde",
    countryCode: "CV",
    currency: "CVE",
    flag: "🇨🇻",
  },
  {
    id: 39,
    name: "Cambodia",
    countryCode: "KH",
    currency: "KHR",
    flag: "🇰🇭",
  },
  {
    id: 40,
    name: "Cameroon",
    countryCode: "CM",
    currency: "XAF",
    flag: "🇨🇲",
  },
  {
    id: 41,
    name: "Canada",
    countryCode: "CA",
    currency: "CAD",
    flag: "🇨🇦",
  },
  {
    id: 42,
    name: "Cayman Islands",
    countryCode: "KY",
    currency: "KYD",
    flag: "🇰🇾",
  },
  {
    id: 43,
    name: "Central African Republic",
    countryCode: "CF",
    currency: "XAF",
    flag: "🇨🇫",
  },
  {
    id: 44,
    name: "Chad",
    countryCode: "TD",
    currency: "XAF",
    flag: "🇹🇩",
  },
  {
    id: 45,
    name: "Chile",
    countryCode: "CL",
    currency: "CLP",
    flag: "🇨🇱",
  },
  {
    id: 46,
    name: "China",
    countryCode: "CN",
    currency: "CNY",
    flag: "🇨🇳",
  },
  {
    id: 47,
    name: "Christmas Island",
    countryCode: "CX",
    currency: "AUD",
    flag: "🇨🇽",
  },
  {
    id: 48,
    name: "Cocos (Keeling) Islands",
    countryCode: "CC",
    currency: "AUD",
    flag: "🇨🇨",
  },
  {
    id: 49,
    name: "Colombia",
    countryCode: "CO",
    currency: "COP",
    flag: "🇨🇴",
  },
  {
    id: 50,
    name: "Comoros",
    countryCode: "KM",
    currency: "KMF",
    flag: "🇰🇲",
  },
  {
    id: 51,
    name: "Congo",
    countryCode: "CG",
    currency: "XAF",
    flag: "🇨🇬",
  },
  {
    id: 52,
    name: "Congo (Democratic Republic of the)",
    countryCode: "CD",
    currency: "CDF",
    flag: "🇨🇩",
  },
  {
    id: 53,
    name: "Cook Islands",
    countryCode: "CK",
    currency: "NZD",
    flag: "🇨🇰",
  },
  {
    id: 54,
    name: "Costa Rica",
    countryCode: "CR",
    currency: "CRC",
    flag: "🇨🇷",
  },
  {
    id: 55,
    name: "Croatia",
    countryCode: "HR",
    currency: "HRK",
    flag: "🇭🇷",
  },
  {
    id: 56,
    name: "Cuba",
    countryCode: "CU",
    currency: "CUP",
    flag: "🇨🇺",
  },
  {
    id: 57,
    name: "Curaçao",
    countryCode: "CW",
    currency: "ANG",
    flag: "🇨🇼",
  },
  {
    id: 58,
    name: "Cyprus",
    countryCode: "CY",
    currency: "EUR",
    flag: "🇨🇾",
  },
  {
    id: 59,
    name: "Czech Republic",
    countryCode: "CZ",
    currency: "CZK",
    flag: "🇨🇿",
  },
  {
    id: 60,
    name: "Denmark",
    countryCode: "DK",
    currency: "DKK",
    flag: "🇩🇰",
  },
  {
    id: 61,
    name: "Djibouti",
    countryCode: "DJ",
    currency: "DJF",
    flag: "🇩🇯",
  },
  {
    id: 62,
    name: "Dominica",
    countryCode: "DM",
    currency: "XCD",
    flag: "🇩🇲",
  },
  {
    id: 63,
    name: "Dominican Republic",
    countryCode: "DO",
    currency: "DOP",
    flag: "🇩🇴",
  },
  {
    id: 64,
    name: "Ecuador",
    countryCode: "EC",
    currency: "USD",
    flag: "🇪🇨",
  },
  {
    id: 65,
    name: "Egypt",
    countryCode: "EG",
    currency: "EGP",
    flag: "🇪🇬",
  },
  {
    id: 66,
    name: "El Salvador",
    countryCode: "SV",
    currency: "USD",
    flag: "🇸🇻",
  },
  {
    id: 67,
    name: "Equatorial Guinea",
    countryCode: "GQ",
    currency: "XAF",
    flag: "🇬🇶",
  },
  {
    id: 68,
    name: "Eritrea",
    countryCode: "ER",
    currency: "ERN",
    flag: "🇪🇷",
  },
  {
    id: 69,
    name: "Estonia",
    countryCode: "EE",
    currency: "EUR",
    flag: "🇪🇪",
  },
  {
    id: 70,
    name: "Eswatini",
    countryCode: "SZ",
    currency: "SZL",
    flag: "🇸🇿",
  },
  {
    id: 71,
    name: "Ethiopia",
    countryCode: "ET",
    currency: "ETB",
    flag: "🇪🇹",
  },
  {
    id: 72,
    name: "Falkland Islands (Malvinas)",
    countryCode: "FK",
    currency: "FKP",
    flag: "🇫🇰",
  },
  {
    id: 73,
    name: "Faroe Islands",
    countryCode: "FO",
    currency: "DKK",
    flag: "🇫🇴",
  },
  {
    id: 74,
    name: "Fiji",
    countryCode: "FJ",
    currency: "FJD",
    flag: "🇫🇯",
  },
  {
    id: 75,
    name: "Finland",
    countryCode: "FI",
    currency: "EUR",
    flag: "🇫🇮",
  },
  {
    id: 76,
    name: "France",
    countryCode: "FR",
    currency: "EUR",
    flag: "🇫🇷",
  },
  {
    id: 77,
    name: "French Guiana",
    countryCode: "GF",
    currency: "EUR",
    flag: "🇬🇫",
  },
  {
    id: 78,
    name: "French Polynesia",
    countryCode: "PF",
    currency: "XPF",
    flag: "🇵🇫",
  },
  {
    id: 79,
    name: "French Southern Territories",
    countryCode: "TF",
    currency: "EUR",
    flag: "🇹🇫",
  },
  {
    id: 80,
    name: "Gabon",
    countryCode: "GA",
    currency: "XAF",
    flag: "🇬🇦",
  },
  {
    id: 81,
    name: "Gambia",
    countryCode: "GM",
    currency: "GMD",
    flag: "🇬🇲",
  },
  {
    id: 82,
    name: "Georgia",
    countryCode: "GE",
    currency: "GEL",
    flag: "🇬🇪",
  },
  {
    id: 83,
    name: "Germany",
    countryCode: "DE",
    currency: "EUR",
    flag: "🇩🇪",
  },
  {
    id: 84,
    name: "Ghana",
    countryCode: "GH",
    currency: "GHS",
    flag: "🇬🇭",
  },
  {
    id: 85,
    name: "Gibraltar",
    countryCode: "GI",
    currency: "GIP",
    flag: "🇬🇮",
  },
  {
    id: 86,
    name: "Greece",
    countryCode: "GR",
    currency: "EUR",
    flag: "🇬🇷",
  },
  {
    id: 87,
    name: "Greenland",
    countryCode: "GL",
    currency: "DKK",
    flag: "🇬🇱",
  },
  {
    id: 88,
    name: "Grenada",
    countryCode: "GD",
    currency: "XCD",
    flag: "🇬🇩",
  },
  {
    id: 89,
    name: "Guadeloupe",
    countryCode: "GP",
    currency: "EUR",
    flag: "🇬🇵",
  },
  {
    id: 90,
    name: "Guam",
    countryCode: "GU",
    currency: "USD",
    flag: "🇬🇺",
  },
  {
    id: 91,
    name: "Guatemala",
    countryCode: "GT",
    currency: "GTQ",
    flag: "🇬🇹",
  },
  {
    id: 92,
    name: "Guernsey",
    countryCode: "GG",
    currency: "GBP",
    flag: "🇬🇬",
  },
  {
    id: 93,
    name: "Guinea",
    countryCode: "GN",
    currency: "GNF",
    flag: "🇬🇳",
  },
  {
    id: 94,
    name: "Guinea-Bissau",
    countryCode: "GW",
    currency: "XOF",
    flag: "🇬🇼",
  },
  {
    id: 95,
    name: "Guyana",
    countryCode: "GY",
    currency: "GYD",
    flag: "🇬🇾",
  },
  {
    id: 96,
    name: "Haiti",
    countryCode: "HT",
    currency: "HTG",
    flag: "🇭🇹",
  },
  {
    id: 97,
    name: "Heard Island and McDonald Islands",
    countryCode: "HM",
    currency: "AUD",
    flag: "🇭🇲",
  },
  {
    id: 98,
    name: "Holy See",
    countryCode: "VA",
    currency: "EUR",
    flag: "🇻🇦",
  },
  {
    id: 99,
    name: "Honduras",
    countryCode: "HN",
    currency: "HNL",
    flag: "🇭🇳",
  },
  {
    id: 100,
    name: "Hong Kong",
    countryCode: "HK",
    currency: "HKD",
    flag: "🇭🇰",
  },
  {
    id: 101,
    name: "Hungary",
    countryCode: "HU",
    currency: "HUF",
    flag: "🇭🇺",
  },
  {
    id: 102,
    name: "Iceland",
    countryCode: "IS",
    currency: "ISK",
    flag: "🇮🇸",
  },
  {
    id: 103,
    name: "India",
    countryCode: "IN",
    currency: "INR",
    flag: "🇮🇳",
  },
  {
    id: 104,
    name: "Indonesia",
    countryCode: "ID",
    currency: "IDR",
    flag: "🇮🇩",
  },
  {
    id: 105,
    name: "Iran (Islamic Republic of)",
    countryCode: "IR",
    currency: "IRR",
    flag: "🇮🇷",
  },
  {
    id: 106,
    name: "Iraq",
    countryCode: "IQ",
    currency: "IQD",
    flag: "🇮🇶",
  },
  {
    id: 107,
    name: "Ireland",
    countryCode: "IE",
    currency: "EUR",
    flag: "🇮🇪",
  },
  {
    id: 108,
    name: "Isle of Man",
    countryCode: "IM",
    currency: "GBP",
    flag: "🇮🇲",
  },
  {
    id: 109,
    name: "Israel",
    countryCode: "IL",
    currency: "ILS",
    flag: "🇮🇱",
  },
  {
    id: 110,
    name: "Italy",
    countryCode: "IT",
    currency: "EUR",
    flag: "🇮🇹",
  },
  {
    id: 111,
    name: "Jamaica",

    countryCode: "JM",
    currency: "JMD",
    flag: "🇯🇲",
  },
  {
    id: 112,
    name: "Japan",
    countryCode: "JP",
    currency: "JPY",
    flag: "🇯🇵",
  },
  {
    id: 113,
    name: "Jersey",
    countryCode: "JE",
    currency: "GBP",
    flag: "🇯🇪",
  },
  {
    id: 114,
    name: "Jordan",
    countryCode: "JO",
    currency: "JOD",
    flag: "🇯🇴",
  },
  {
    id: 115,
    name: "Kazakhstan",
    countryCode: "KZ",
    currency: "KZT",
    flag: "🇰🇿",
  },
  {
    id: 116,
    name: "Kenya",
    countryCode: "KE",
    currency: "KES",
    flag: "🇰🇪",
  },
  {
    id: 117,
    name: "Kiribati",
    countryCode: "KI",
    currency: "AUD",
    flag: "🇰🇮",
  },
  {
    id: 118,
    name: "Korea (Democratic People's Republic of)",
    countryCode: "KP",
    currency: "KPW",
    flag: "🇰🇵",
  },
  {
    id: 119,
    name: "Korea (Republic of)",
    countryCode: "KR",
    currency: "KRW",
    flag: "🇰🇷",
  },
  {
    id: 120,
    name: "Kuwait",
    countryCode: "KW",
    currency: "KWD",
    flag: "🇰🇼",
  },
  {
    id: 121,
    name: "Kyrgyzstan",
    countryCode: "KG",
    currency: "KGS",
    flag: "🇰🇬",
  },
  {
    id: 122,
    name: "Lao People's Democratic Republic",
    countryCode: "LA",
    currency: "LAK",
    flag: "🇱🇦",
  },
  {
    id: 123,
    name: "Latvia",
    countryCode: "LV",
    currency: "EUR",
    flag: "🇱🇻",
  },
  {
    id: 124,
    name: "Lebanon",
    countryCode: "LB",
    currency: "LBP",
    flag: "🇱🇧",
  },
  {
    id: 125,
    name: "Lesotho",
    countryCode: "LS",
    currency: "LSL",
    flag: "🇱🇸",
  },
  {
    id: 126,
    name: "Liberia",
    countryCode: "LR",
    currency: "LRD",
    flag: "🇱🇷",
  },
  {
    id: 127,
    name: "Libya",
    countryCode: "LY",
    currency: "LYD",
    flag: "🇱🇾",
  },
  {
    id: 128,
    name: "Liechtenstein",
    countryCode: "LI",
    currency: "CHF",
    flag: "🇱🇮",
  },
  {
    id: 129,
    name: "Lithuania",
    countryCode: "LT",
    currency: "EUR",
    flag: "🇱🇹",
  },
  {
    id: 130,
    name: "Luxembourg",
    countryCode: "LU",
    currency: "EUR",
    flag: "🇱🇺",
  },
  {
    id: 131,
    name: "Macao",
    countryCode: "MO",
    currency: "MOP",
    flag: "🇲🇴",
  },
  {
    id: 132,
    name: "Madagascar",
    countryCode: "MG",
    currency: "MGA",
    flag: "🇲🇬",
  },
  {
    id: 133,
    name: "Malawi",
    countryCode: "MW",
    currency: "MWK",
    flag: "🇲🇼",
  },
  {
    id: 134,
    name: "Malaysia",
    countryCode: "MY",
    currency: "MYR",
    flag: "🇲🇾",
  },
  {
    id: 135,
    name: "Maldives",
    countryCode: "MV",
    currency: "MVR",
    flag: "🇲🇻",
  },
  {
    id: 136,
    name: "Mali",
    countryCode: "ML",
    currency: "XOF",
    flag: "🇲🇱",
  },
  {
    id: 137,
    name: "Malta",
    countryCode: "MT",
    currency: "EUR",
    flag: "🇲🇹",
  },
  {
    id: 138,
    name: "Marshall Islands",
    countryCode: "MH",
    currency: "USD",
    flag: "🇲🇭",
  },
  {
    id: 139,
    name: "Martinique",
    countryCode: "MQ",
    currency: "EUR",
    flag: "🇲🇶",
  },
  {
    id: 140,
    name: "Mauritania",
    countryCode: "MR",
    currency: "MRU",
    flag: "🇲🇷",
  },
  {
    id: 141,
    name: "Mauritius",
    countryCode: "MU",
    currency: "MUR",
    flag: "🇲🇺",
  },
  {
    id: 142,
    name: "Mayotte",
    countryCode: "YT",
    currency: "EUR",
    flag: "🇾🇹",
  },
  {
    id: 143,
    name: "Mexico",
    countryCode: "MX",
    currency: "MXN",
    flag: "🇲🇽",
  },
  {
    id: 144,
    name: "Micronesia (Federated States of)",
    countryCode: "FM",
    currency: "USD",
    flag: "🇫🇲",
  },
  {
    id: 145,
    name: "Moldova (Republic of)",
    countryCode: "MD",
    currency: "MDL",
    flag: "🇲🇩",
  },
  {
    id: 146,
    name: "Monaco",
    countryCode: "MC",
    currency: "EUR",
    flag: "🇲🇨",
  },
  {
    id: 147,
    name: "Mongolia",
    countryCode: "MN",
    currency: "MNT",
    flag: "🇲🇳",
  },
  {
    id: 148,

    name: "Montenegro",
    countryCode: "ME",
    currency: "EUR",
    flag: "🇲🇪",
  },
  {
    id: 149,
    name: "Montserrat",
    countryCode: "MS",
    currency: "XCD",
    flag: "🇲🇸",
  },
  {
    id: 150,
    name: "Morocco",
    countryCode: "MA",
    currency: "MAD",
    flag: "🇲🇦",
  },
  {
    id: 151,
    name: "Mozambique",
    countryCode: "MZ",
    currency: "MZN",
    flag: "🇲🇿",
  },
  {
    id: 152,
    name: "Myanmar",
    countryCode: "MM",
    currency: "MMK",
    flag: "🇲🇲",
  },
  {
    id: 153,
    name: "Namibia",
    countryCode: "NA",
    currency: "NAD",
    flag: "🇳🇦",
  },
  {
    id: 154,
    name: "Nauru",
    countryCode: "NR",
    currency: "AUD",
    flag: "🇳🇷",
  },
  {
    id: 155,
    name: "Nepal",
    countryCode: "NP",
    currency: "NPR",
    flag: "🇳🇵",
  },
  {
    id: 156,
    name: "Netherlands",
    countryCode: "NL",
    currency: "EUR",
    flag: "🇳🇱",
  },
  {
    id: 157,
    name: "New Caledonia",
    countryCode: "NC",
    currency: "XPF",
    flag: "🇳🇨",
  },
  {
    id: 158,
    name: "New Zealand",
    countryCode: "NZ",
    currency: "NZD",
    flag: "🇳🇿",
  },
  {
    id: 159,
    name: "Nicaragua",
    countryCode: "NI",
    currency: "NIO",
    flag: "🇳🇮",
  },
  {
    id: 160,
    name: "Niger",
    countryCode: "NE",
    currency: "XOF",
    flag: "🇳🇪",
  },
  {
    id: 161,
    name: "Nigeria",
    countryCode: "NG",
    currency: "NGN",
    flag: "🇳🇬",
  },
  {
    id: 162,
    name: "Niue",
    countryCode: "NU",
    currency: "NZD",
    flag: "🇳🇺",
  },
  {
    id: 163,
    name: "Norfolk Island",
    countryCode: "NF",
    currency: "AUD",
    flag: "🇳🇫",
  },
  {
    id: 164,
    name: "North Macedonia",
    countryCode: "MK",
    currency: "MKD",
    flag: "🇲🇰",
  },
  {
    id: 165,
    name: "Northern Mariana Islands",
    countryCode: "MP",
    currency: "USD",
    flag: "🇲🇵",
  },
  {
    id: 166,
    name: "Norway",
    countryCode: "NO",
    currency: "NOK",
    flag: "🇳🇴",
  },
  {
    id: 167,
    name: "Oman",
    countryCode: "OM",
    currency: "OMR",
    flag: "🇴🇲",
  },
  {
    id: 168,
    name: "Pakistan",
    countryCode: "PK",
    currency: "PKR",
    flag: "🇵🇰",
  },
  {
    id: 169,
    name: "Palau",
    countryCode: "PW",
    currency: "USD",
    flag: "🇵🇼",
  },
  {
    id: 170,
    name: "Palestine, State of",
    countryCode: "PS",
    currency: "ILS",
    flag: "🇵🇸",
  },
  {
    id: 171,
    name: "Panama",
    countryCode: "PA",
    currency: "PAB",
    flag: "🇵🇦",
  },
  {
    id: 172,
    name: "Papua New Guinea",
    countryCode: "PG",
    currency: "PGK",
    flag: "🇵🇬",
  },
  {
    id: 173,
    name: "Paraguay",
    countryCode: "PY",
    currency: "PYG",
    flag: "🇵🇾",
  },
  {
    id: 174,
    name: "Peru",
    countryCode: "PE",
    currency: "PEN",
    flag: "🇵🇪",
  },
  {
    id: 175,
    name: "Philippines",
    countryCode: "PH",
    currency: "PHP",
    flag: "🇵🇭",
  },
  {
    id: 176,
    name: "Pitcairn",
    countryCode: "PN",
    currency: "NZD",
    flag: "🇵🇳",
  },
  {
    id: 177,
    name: "Poland",
    countryCode: "PL",
    currency: "PLN",
    flag: "🇵🇱",
  },
  {
    id: 178,
    name: "Portugal",
    countryCode: "PT",
    currency: "EUR",
    flag: "🇵🇹",
  },
  {
    id: 179,
    name: "Puerto Rico",
    countryCode: "PR",
    currency: "USD",
    flag: "🇵🇷",
  },
  {
    id: 180,
    name: "Qatar",
    countryCode: "QA",
    currency: "QAR",
    flag: "🇶🇦",
  },
  {
    id: 181,
    name: "Réunion",
    countryCode: "RE",
    currency: "EUR",
    flag: "🇷🇪",
  },
  {
    id: 182,
    name: "Romania",
    countryCode: "RO",
    currency: "RON",
    flag: "🇷🇴",
  },
  {
    id: 183,
    name: "Russian Federation",
    countryCode: "RU",
    currency: "RUB",
    flag: "🇷🇺",
  },
  {
    id: 184,
    name: "Rwanda",
    countryCode: "RW",
    currency: "RWF",
    flag: "🇷🇼",
  },
  {
    id: 185,
    name: "Saint Barthélemy",

    countryCode: "BL",
    currency: "EUR",
    flag: "🇧🇱",
  },
  {
    id: 186,
    name: "Saint Helena, Ascension and Tristan da Cunha",
    countryCode: "SH",
    currency: "SHP",
    flag: "🇸🇭",
  },
  {
    id: 187,
    name: "Saint Kitts and Nevis",
    countryCode: "KN",
    currency: "XCD",
    flag: "🇰🇳",
  },
  {
    id: 188,
    name: "Saint Lucia",
    countryCode: "LC",
    currency: "XCD",
    flag: "🇱🇨",
  },
  {
    id: 189,
    name: "Saint Martin (French part)",
    countryCode: "MF",
    currency: "EUR",
    flag: "🇲🇫",
  },
  {
    id: 190,
    name: "Saint Pierre and Miquelon",
    countryCode: "PM",
    currency: "EUR",
    flag: "🇵🇲",
  },
  {
    id: 191,
    name: "Saint Vincent and the Grenadines",
    countryCode: "VC",
    currency: "XCD",
    flag: "🇻🇨",
  },
  {
    id: 192,
    name: "Samoa",
    countryCode: "WS",
    currency: "WST",
    flag: "🇼🇸",
  },
  {
    id: 193,
    name: "San Marino",
    countryCode: "SM",
    currency: "EUR",
    flag: "🇸🇲",
  },
  {
    id: 194,
    name: "Sao Tome and Principe",
    countryCode: "ST",
    currency: "STN",
    flag: "🇸🇹",
  },
  {
    id: 195,
    name: "Saudi Arabia",
    countryCode: "SA",
    currency: "SAR",
    flag: "🇸🇦",
  },
  {
    id: 196,
    name: "Senegal",
    countryCode: "SN",
    currency: "XOF",
    flag: "🇸🇳",
  },
  {
    id: 197,
    name: "Serbia",
    countryCode: "RS",
    currency: "RSD",
    flag: "🇷🇸",
  },
  {
    id: 198,
    name: "Seychelles",
    countryCode: "SC",
    currency: "SCR",
    flag: "🇸🇨",
  },
  {
    id: 199,
    name: "Sierra Leone",
    countryCode: "SL",
    currency: "SLL",
    flag: "🇸🇱",
  },
  {
    id: 200,
    name: "Singapore",
    countryCode: "SG",
    currency: "SGD",
    flag: "🇸🇬",
  },
  {
    id: 201,
    name: "Sint Maarten (Dutch part)",
    countryCode: "SX",
    currency: "ANG",
    flag: "🇸🇽",
  },
  {
    id: 202,
    name: "Slovakia",
    countryCode: "SK",
    currency: "EUR",
    flag: "🇸🇰",
  },
  {
    id: 203,
    name: "Slovenia",
    countryCode: "SI",
    currency: "EUR",
    flag: "🇸🇮",
  },
  {
    id: 204,
    name: "Solomon Islands",
    countryCode: "SB",
    currency: "SBD",
    flag: "🇸🇧",
  },
  {
    id: 205,
    name: "Somalia",
    countryCode: "SO",
    currency: "SOS",
    flag: "🇸🇴",
  },
  {
    id: 206,
    name: "South Africa",
    countryCode: "ZA",
    currency: "ZAR",
    flag: "🇿🇦",
  },
  {
    id: 207,
    name: "South Georgia and the South Sandwich Islands",
    countryCode: "GS",
    currency: "GBP",
    flag: "🇬🇸",
  },
  {
    id: 208,
    name: "South Sudan",
    countryCode: "SS",
    currency: "SSP",
    flag: "🇸🇸",
  },
  {
    id: 209,
    name: "Spain",
    countryCode: "ES",
    currency: "EUR",
    flag: "🇪🇸",
  },
  {
    id: 210,
    name: "Sri Lanka",
    countryCode: "LK",
    currency: "LKR",
    flag: "🇱🇰",
  },
  {
    id: 211,
    name: "Sudan",
    countryCode: "SD",
    currency: "SDG",
    flag: "🇸🇩",
  },
  {
    id: 212,
    name: "Suriname",
    countryCode: "SR",
    currency: "SRD",
    flag: "🇸🇷",
  },
  {
    id: 213,
    name: "Svalbard and Jan Mayen",
    countryCode: "SJ",
    currency: "NOK",
    flag: "🇸🇯",
  },
  {
    id: 214,
    name: "Sweden",
    countryCode: "SE",
    currency: "SEK",
    flag: "🇸🇪",
  },
  {
    id: 215,
    name: "Switzerland",
    countryCode: "CH",
    currency: "CHF",
    flag: "🇨🇭",
  },
  {
    id: 216,
    name: "Syrian Arab Republic",
    countryCode: "SY",
    currency: "SYP",
    flag: "🇸🇾",
  },
  {
    id: 217,
    name: "Taiwan",
    countryCode: "TW",
    currency: "TWD",
    flag: "🇹🇼",
  },
  {
    id: 218,
    name: "Tajikistan",
    countryCode: "TJ",
    currency: "TJS",
    flag: "🇹🇯",
  },
  {
    id: 219,
    name: "Tanzania, United Republic of",
    countryCode: "TZ",
    currency: "TZS",
    flag: "🇹🇿",
  },
  {
    id: 220,
    name: "Thailand",
    countryCode: "TH",
    currency: "THB",
    flag: "🇹🇭",
  },
  {
    id: 221,
    name: "Timor-Leste",
    countryCode: "TL",

    currency: "USD",
    flag: "🇹🇱",
  },
  {
    id: 222,
    name: "Togo",
    countryCode: "TG",
    currency: "XOF",
    flag: "🇹🇬",
  },
  {
    id: 223,
    name: "Tokelau",
    countryCode: "TK",
    currency: "NZD",
    flag: "🇹🇰",
  },
  {
    id: 224,
    name: "Tonga",
    countryCode: "TO",
    currency: "TOP",
    flag: "🇹🇴",
  },
  {
    id: 225,
    name: "Trinidad and Tobago",
    countryCode: "TT",
    currency: "TTD",
    flag: "🇹🇹",
  },
  {
    id: 226,
    name: "Tunisia",
    countryCode: "TN",
    currency: "TND",
    flag: "🇹🇳",
  },
  {
    id: 227,
    name: "Turkey",
    countryCode: "TR",
    currency: "TRY",
    flag: "🇹🇷",
  },
  {
    id: 228,
    name: "Turkmenistan",
    countryCode: "TM",
    currency: "TMT",
    flag: "🇹🇲",
  },
  {
    id: 229,
    name: "Turks and Caicos Islands",
    countryCode: "TC",
    currency: "USD",
    flag: "🇹🇨",
  },
  {
    id: 230,
    name: "Tuvalu",
    countryCode: "TV",
    currency: "AUD",
    flag: "🇹🇻",
  },
  {
    id: 231,
    name: "Uganda",
    countryCode: "UG",
    currency: "UGX",
    flag: "🇺🇬",
  },
  {
    id: 232,
    name: "Ukraine",
    countryCode: "UA",
    currency: "UAH",
    flag: "🇺🇦",
  },
  {
    id: 233,
    name: "United Arab Emirates",
    countryCode: "AE",
    currency: "AED",
    flag: "🇦🇪",
  },
  {
    id: 234,
    name: "United Kingdom of Great Britain and Northern Ireland",
    countryCode: "GB",
    currency: "GBP",
    flag: "🇬🇧",
  },
  {
    id: 235,
    name: "United States of America",
    countryCode: "US",
    currency: "USD",
    flag: "🇺🇸",
  },
  {
    id: 236,
    name: "Uruguay",
    countryCode: "UY",
    currency: "UYU",
    flag: "🇺🇾",
  },
  {
    id: 237,
    name: "Uzbekistan",
    countryCode: "UZ",
    currency: "UZS",
    flag: "🇺🇿",
  },
  {
    id: 238,
    name: "Vanuatu",
    countryCode: "VU",
    currency: "VUV",
    flag: "🇻🇺",
  },
  {
    id: 239,
    name: "Venezuela (Bolivarian Republic of)",
    countryCode: "VE",
    currency: "VES",
    flag: "🇻🇪",
  },
  {
    id: 240,
    name: "Viet Nam",
    countryCode: "VN",
    currency: "VND",
    flag: "🇻🇳",
  },
  {
    id: 241,
    name: "Wallis and Futuna",
    countryCode: "WF",
    currency: "XPF",
    flag: "🇼🇫",
  },
  {
    id: 242,
    name: "Western Sahara",
    countryCode: "EH",
    currency: "MAD",
    flag: "🇪🇭",
  },
  {
    id: 243,
    name: "Yemen",
    countryCode: "YE",
    currency: "YER",
    flag: "🇾🇪",
  },
  {
    id: 244,
    name: "Zambia",
    countryCode: "ZM",
    currency: "ZMW",
    flag: "🇿🇲",
  },
  {
    id: 245,
    name: "Zimbabwe",
    countryCode: "ZW",
    currency: "ZWL",
    flag: "🇿🇼",
  },
];
