export const districts = [
  {
    id: 1,
    name: "Ampara",
    districtCode: "Ampara",
    provinceCode: "Eastern",
  },
  {
    id: 2,
    name: "Anuradhapura",
    districtCode: "Anuradhapura",
    provinceCode: "North-Central",
  },
  {
    id: 3,
    name: "Badulla",
    districtCode: "Badulla",
    provinceCode: "Uva",
  },
  {
    id: 4,
    name: "Batticaloa",
    districtCode: "Batticaloa",
    provinceCode: "Eastern",
  },
  {
    id: 5,
    name: "Colombo",
    districtCode: "Colombo",
    provinceCode: "Western",
  },
  {
    id: 6,
    name: "Galle",
    districtCode: "Galle",
    provinceCode: "Southern",
  },
  {
    id: 7,
    name: "Gampaha",
    districtCode: "Gampaha",
    provinceCode: "Western",
  },
  {
    id: 8,
    name: "Hambantota",
    districtCode: "Hambantota",
    provinceCode: "Southern",
  },
  {
    id: 9,
    name: "Jaffna",
    districtCode: "Jaffna",
    provinceCode: "Northern",
  },
  {
    id: 10,
    name: "Kalutara",
    districtCode: "Kalutara",
    provinceCode: "Western",
  },
  {
    id: 11,
    name: "Kandy",
    districtCode: "Kandy",
    provinceCode: "Central",
  },
  {
    id: 12,
    name: "Kegalle",
    districtCode: "Kegalle",
    provinceCode: "Sabaragamuva",
  },
  {
    id: 13,
    name: "Kilinochchi",
    districtCode: "Kilinochchi",
    provinceCode: "Northern",
  },
  {
    id: 14,
    name: "Kurunegala",
    districtCode: "Kurunegala",
    provinceCode: "North-Western",
  },
  {
    id: 15,
    name: "Mannar",
    districtCode: "Mannar",
    provinceCode: "Northern",
  },
  {
    id: 16,
    name: "Matale",
    districtCode: "Matale",
    provinceCode: "Central",
  },
  {
    id: 17,
    name: "Matara",
    districtCode: "Matara",
    provinceCode: "Southern",
  },
  {
    id: 18,
    name: "Moneragala",
    districtCode: "Moneragala",
    provinceCode: "Uva",
  },
  {
    id: 19,
    name: "Mullaitivu",
    districtCode: "Mullaitivu",
    provinceCode: "Northern",
  },
  {
    id: 20,
    name: "Nuwara Eliya",
    districtCode: "Nuwara Eliya",
    provinceCode: "Central",
  },
  {
    id: 21,
    name: "Polonnaruwa",
    districtCode: "Polonnaruwa",
    provinceCode: "North-Central",
  },
  {
    id: 22,
    name: "Puttalam",
    districtCode: "Puttalam",
    provinceCode: "North-Western",
  },
  {
    id: 23,
    name: "Ratnapura",
    districtCode: "Ratnapura",
    provinceCode: "Sabaragamuva",
  },
  {
    id: 24,
    name: "Trincomalee",
    districtCode: "Trincomalee",
    provinceCode: "Eastern",
  },
  {
    id: 25,
    name: "Vavuniya",
    districtCode: "Vavuniya",
    provinceCode: "Northern",
  },
];
